### ISSUE TITLE
[Suggestion] Messages

### ISSUE THREAD

**Issue by KhrysAK47** [LagBug/Emailer#1]
Hello! My suggestion/idea consists in adding a few new options to the plugin, more precisely a message to send players that haven't linked an email to their account, as well as a delay to send the message after the join, and an enable/disable option, here's an example of the configuration:

```
UnlinkedJoinMessage:
    enabled: true/false 
    message: '&cYou have not linked an email with your account yet!' 
    delay: 20 # in ticks
```
